spring.datasource.url=jdbc:postgresql://localhost:5433/benchmark
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=10
logging.level.com.zaxxer.hikari=DEBUG
